apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: default
  labels:
    app: HashiCorpVault
spec:
  containers:
  - name: vault
    image: vault
    ports:
    - containerPort: 8200
      name:  http